### PR TITLE
Version 3.0 of @rocketseat/gatsby-theme-docs

### PR DESCRIPTION
**Pull request by jpedroschmitz**
Based on discussions around our project we decided to go ahead and give it a try to TypeScript. This PR will convert both docs themes (`theme-docs` and `theme-docs-core`) to TypeScript! 🎉

Edit: Since we started the TypeScript migration we decided to move on and already work on a version 3.0 of the theme, that will add Algolia search, convert to Theme UI and also add a dark option to the project.

We are currently working on such features and plan to release it soon.

### CODE REVIEW

**Comment by Hrishikesh-K** [comment]
Hey @jpedroschmitz, I was planning to start customizing the theme for my use case and I came across this PR. From what I can see, the information shows the project is closed, so, does it mean that the development for this has been stopped or shall I wait for sometime if you're close to finish this?

**Comment by jpedroschmitz** [comment]
Hey @Hrishikesh-K, this project is on wait for now. We plan to work on it again in the next weeks, as soon we get the new design. But probably we will release it as a new advanced docs theme, and keep `@rocketseat/gatsby-theme-docs` just for smaller projects.

The idea is to include a dark mode, search, different navigation, a dedicated home (other than the docs page) and ship other enhancements.

**Comment by Hrishikesh-K** [comment]
@jpedroschmitz It's great to know that at least it's not closed. Good luck with the release.

**Comment by jpedroschmitz** [comment]
Closing it by now since we have decided not to continue with this new version.

**Pull request closed without merging**
